---
- name: Apply openshift-vcenter-level role to vCenter
  command: "govc permissions.set --principal {{ openshift.vcenter_svc_account }} -role openshift-vcenter-level -propagate=false /"

- name: Apply openshift-datacenter-level role to vCenter Datacenter
  command: "govc permissions.set --principal {{ openshift.vcenter_svc_account }} -role openshift-datacenter-level -propagate=true /{{ vcenter.datacenter }}"

- name: Apply openshift-cluster-level role to vCenter Cluster
  command: "govc permissions.set --principal {{ openshift.vcenter_svc_account }} -role openshift-cluster-level -propagate=true /{{ vcenter.datacenter }}/host/{{ vcenter.cluster }}"

- name: Apply openshift-datastore-level role to vCenter Datastore
  command: "govc permissions.set --principal {{ openshift.vcenter_svc_account }} -role openshift-datastore-level -propagate=false /{{ vcenter.datacenter }}/datastore/{{ vcenter.datastore }}"

- name: Apply openshift-portgroup-level role to vCenter PortGroup
  command: "govc permissions.set --principal {{ openshift.vcenter_svc_account }} -role openshift-portgroup-level -propagate=false /{{ vcenter.datacenter }}/network/{{ vcenter.network }}"
