---
- name: Create bin and downloads folder
  file:
    path: "{{ playbook_dir }}/{{ item }}"
    state: directory
  with_items: ["bin", "downloads"]

- name: Download govc
  get_url:
    url: "{{ download.govc }}"
    dest: "{{ playbook_dir }}/downloads/govc.gz"
    validate_certs: no

- name: Unarchive govc
  shell: gzip -dc "{{ playbook_dir }}/downloads/govc.gz" > "{{ playbook_dir }}/bin/govc" # noqa 301

- name: Make govc executable
  file:
    path: "{{ playbook_dir }}/bin/govc"
    mode: '775'
