---
- name: Create bin and downloads folder
  file:
    path: "{{ playbook_dir }}/{{ item }}"
    state: directory
  with_items: ["bin", "downloads"]

- name: Download govc
  get_url:
    url: "{{ download.govc }}"
    dest: "{{ playbook_dir }}/downloads/govc.tar.gz"
    validate_certs: no

- name: Unarchive govc and make govc executable
  unarchive:
    src: "{{ playbook_dir }}/downloads/govc.tar.gz"
    dest: "{{ playbook_dir }}/bin/"
    mode: '0755'
